# Generated by Django 4.2.3 on 2023-08-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_images/')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='images',
            field=models.ManyToManyField(to='User.image'),
        ),
    ]
